import React, { useState } from 'react';
import { Search, Copy, Check, Filter } from 'lucide-react';

const GLOSSARY_ITEMS = [
  {
    term: "Retrieval-Augmented Generation (RAG)",
    category: "LLM",
    definition: "An architecture that retrieves document chunks from an external database to feed into an LLM prompt as context, enabling factually grounded generations.",
    analogy: "Like an open-book exam: instead of guessing, you search the book and copy the correct formula into your answer sheet.",
    oneLiner: "RAG retrieves external contexts and augments prompts to reduce model hallucinations."
  },
  {
    term: "Vector Embedding",
    category: "VECTORS",
    definition: "A dense array of high-dimensional numbers generated by a model to capture and represent the semantic meaning of data.",
    analogy: "A latitude/longitude coordinate pair, but instead of mapping global geography, it maps semantic human meanings.",
    oneLiner: "Embeddings represent conceptual meaning as mathematical coordinates in high-dimensional space."
  },
  {
    term: "Quantization",
    category: "INFRA",
    definition: "Converting model weights to lower-precision formats (like float32 to int8) to reduce model memory sizes and accelerate inference.",
    analogy: "Converting a high-resolution lossless image to a compressed JPG to save disk space with minimal loss in clarity.",
    oneLiner: "Quantization lowers weight bit-precision to fit large models onto cheaper GPUs/CPUs."
  },
  {
    term: "Cosine Similarity",
    category: "VECTORS",
    definition: "A metric that measures the angular distance between two vectors in multi-dimensional space to evaluate semantic similarity.",
    analogy: "Checking how close two compass needles point, regardless of how long the needles are.",
    oneLiner: "Cosine similarity measures vector alignment to determine semantic matching scores."
  },
  {
    term: "RLHF",
    category: "LLM",
    definition: "Reinforcement Learning from Human Feedback: training an LLM by scoring outputs using a human-preferences reward model.",
    analogy: "Training a puppy by giving it treats when it sits (reward model) and ignoring it when it barks.",
    oneLiner: "RLHF aligns LLM response tones to human safety and helpfulness guidelines."
  },
  {
    term: "Epoch",
    category: "DL",
    definition: "One full pass of the entire training dataset through a model during the parameter training phase.",
    analogy: "Reading a textbook from cover to cover exactly once during a semester's study.",
    oneLiner: "An epoch is a single complete cycle through the training dataset."
  },
  {
    term: "Learning Rate",
    category: "DL",
    definition: "A hyperparameter that scales the size of weight updates calculated during gradient descent.",
    analogy: "The stride size of a hiker: walking too fast causes overshooting; walking too slowly takes forever to reach the bottom.",
    oneLiner: "Learning rate governs parameter update step sizes to balance training speed and stability."
  },
  {
    term: "Hallucination",
    category: "LLM",
    definition: "When a generative model outputs text that is grammatically correct but factually incorrect or unsupported by context.",
    analogy: "A student confidently writing a detailed, fictitious history answer to pass an essay test.",
    oneLiner: "Hallucinations are incorrect facts outputted with high confidence by prediction models."
  },
  {
    term: "Mixture of Experts (MoE)",
    category: "LLM",
    definition: "A model design where input tokens are routed dynamically to specific sub-expert networks instead of executing the entire model.",
    analogy: "A medical clinic that routes bone fractures to orthopedists and skin rashes to dermatologists.",
    oneLiner: "MoE routes prompts dynamically to specialists to reduce inference computations."
  },
  {
    term: "GPU vs TPU",
    category: "INFRA",
    definition: "GPU (Graphics Processing Unit) handles general parallel operations. TPU (Tensor Processing Unit) is Google's custom chip built specifically for matrix math.",
    analogy: "GPU is a generic multi-lane highway; TPU is a high-speed express train track custom built for one specific route.",
    oneLiner: "TPUs are custom hardware accelerators optimized specifically for tensor matrix multiplications."
  },
  {
    term: "Epoch vs Batch Size",
    category: "ML",
    definition: "Epoch is the total pass count. Batch size is the number of samples evaluated before parameters are updated.",
    analogy: "An epoch is studying the entire vocabulary booklet. A batch is learning 10 words before pausing to correct your notes.",
    oneLiner: "Batch size controls parameter update frequency; epoch tracks total passes."
  },
  {
    term: "Decision Boundary",
    category: "ML",
    definition: "The geometric partition boundary separating different classification categories in a dataset.",
    analogy: "The physical fence dividing residential property lines from commercial zones.",
    oneLiner: "Decision boundaries map thresholds separating distinct data classes."
  }
];

export default function AimlCheatSheet() {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('ALL');
  const [copiedIndex, setCopiedIndex] = useState(null);

  const categories = ['ALL', 'LLM', 'VECTORS', 'DL', 'ML', 'INFRA'];

  const filtered = GLOSSARY_ITEMS.filter(item => {
    const matchesSearch = item.term.toLowerCase().includes(search.toLowerCase()) || 
                          item.definition.toLowerCase().includes(search.toLowerCase());
    const matchesCategory = category === 'ALL' || item.category === category;
    return matchesSearch && matchesCategory;
  });

  const handleCopy = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="bg-white/60 dark:bg-black/60 backdrop-blur-md border border-gray-250 dark:border-[#333] rounded-2xl p-6 md:p-8 shadow-lg space-y-6">
      
      {/* Header */}
      <div className="border-b border-gray-150 dark:border-[#333] pb-4">
        <h2 className="text-xl font-black text-gray-900 dark:text-white font-mono uppercase tracking-wide">
          📋 AI/ML Interview Glossary Cheat Sheet
        </h2>
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-1.5 font-light leading-relaxed">
          Quick search SDE analogies, interview one-liners, and conceptual definitions for active revision.
        </p>
      </div>

      {/* Filters Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        {/* Search */}
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search keywords or definitions..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs bg-gray-50/50 dark:bg-black/40 border border-gray-200 dark:border-neutral-800 rounded-xl font-mono text-gray-800 dark:text-gray-300 focus:outline-none focus:border-indigo-500 transition-all"
          />
        </div>

        {/* Filter Pills */}
        <div className="flex items-center space-x-1.5 overflow-x-auto pb-1 md:pb-0 scrollbar-none">
          <Filter className="h-3.5 w-3.5 text-gray-400 flex-shrink-0 mr-1" />
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setCategory(cat)}
              className={`px-3 py-1 text-[10px] font-mono font-bold rounded-lg border transition-all cursor-pointer
                ${category === cat 
                  ? 'bg-indigo-500/10 text-indigo-500 border-indigo-500/30' 
                  : 'bg-transparent text-gray-550 dark:text-gray-450 border-gray-200 dark:border-neutral-900 hover:border-indigo-500/20'}`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Grid List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filtered.length > 0 ? (
          filtered.map((item, idx) => (
            <div 
              key={idx}
              className="p-5 border border-gray-200 dark:border-neutral-900 bg-white/40 dark:bg-neutral-950/20 hover:border-indigo-500/30 rounded-xl flex flex-col justify-between space-y-4 hover:shadow-md transition-all group relative"
            >
              {/* Top Row */}
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="px-2 py-0.5 bg-indigo-500/10 text-indigo-500 text-[8px] font-mono font-black uppercase rounded">
                    {item.category}
                  </span>
                  <button
                    onClick={() => handleCopy(`${item.term}: ${item.definition}`, idx)}
                    className="p-1 hover:bg-gray-100 dark:hover:bg-neutral-900 rounded text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 transition-all opacity-0 group-hover:opacity-100 absolute right-3 top-3"
                    title="Copy Definition"
                  >
                    {copiedIndex === idx ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                  </button>
                </div>
                <h3 className="text-sm font-black text-gray-800 dark:text-gray-250 font-mono">
                  {item.term}
                </h3>
              </div>

              {/* Definition */}
              <p className="text-xs text-gray-650 dark:text-gray-400 font-light leading-relaxed">
                {item.definition}
              </p>

              {/* Analogy Box */}
              <div className="p-3 bg-neutral-100/60 dark:bg-neutral-900/30 border-l-2 border-slate-400 dark:border-neutral-700 rounded-r-lg">
                <span className="block text-[8px] font-mono text-slate-400 dark:text-neutral-500 uppercase tracking-widest font-black mb-0.5">💡 SDE Analogy</span>
                <p className="text-[10.5px] italic text-gray-500 dark:text-gray-400 leading-normal font-sans">
                  {item.analogy}
                </p>
              </div>

              {/* Speak ready summary */}
              <div>
                <span className="block text-[8px] font-mono text-indigo-400/80 uppercase tracking-widest font-black mb-0.5">🗣️ Speak-ready Answer</span>
                <p className="text-[10.5px] font-mono font-bold text-indigo-500/90 leading-normal">
                  {item.oneLiner}
                </p>
              </div>
            </div>
          ))
        ) : (
          <div className="col-span-2 flex flex-col items-center justify-center py-10 border border-dashed border-gray-250 dark:border-neutral-800 rounded-xl text-center text-gray-450">
            <span className="text-2xl">🔎</span>
            <span className="text-xs font-mono mt-2">No matching glossary items found.</span>
          </div>
        )}
      </div>

    </div>
  );
}
