server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patternforge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

patternforge:
  jwt:
    secret: 405040148695mu2q9380cg4lt4t94c0f16n7ftab9p0osupersecretkeyforpatternforgeapplication
    expiration-ms: 86400000 # 24 Hours
  pdf:
    path: C:\Users\rajsh\Downloads\Striver_A2Z_Master_DSA_Database.pdf
  code:
    temp-dir: C:\Users\rajsh\Desktop\DSAremastered\backend\temp

gemini:
  api-key: ${GEMINI_API_KEY:}
